name: Main

on:
  push:
    branches:
      - main

jobs:
  Debug:
    name: "Build debug"
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Get Flutter Version
        id: flutter_version
        uses: bungabear/flutter_version_read@main
        with:
          file: ${{ github.workspace }}/pubspec.yaml

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: "Flutter config"
        run: flutter config --no-analytics

      - name: "Flutter pub get"
        run: flutter pub get

      - name: "Flutter pub get"
        run: flutter pub get

      - name: "Build apk (debug)"
        run: flutter build apk --debug

      - name: "Upload artifact android application (apk)"
        uses: actions/upload-artifact@v4
        with:
          name: iperon-android-${{ steps.flutter_version.outputs.version_number }}.apk
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30
