name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  version:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Get Flutter Version
        id: flutter_version
        uses: bungabear/flutter_version_read@main
        with:
          file: ./pubspec.yml
      - name: Flutter App Version Number
        run: echo 'version_number:' ${{ steps.flutter_version.outputs.version_number }}

      - name: Flutter App Build Number
        run: echo 'build_number:' ${{ steps.flutter_version.outputs.build_number }}

      - name: Flutter App Version Number Major
        run: echo 'version_number_major:' ${{ steps.flutter_version.outputs.version_number_major }}

      - name: Flutter App Version Number Minor
        run: echo 'version_number:' ${{ steps.flutter_version.outputs.version_number_minor }}

      - name: Flutter App Version Number Patch
        run: echo 'version_number:' ${{ steps.flutter_version.outputs.version_number_patch }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
      - run: flutter build appbundle
      - run: flutter build ios --release --no-codesign

#  Linter:
#    uses: github.com/iperon-org/app/.github/workflows/_linter.yaml@ci_cd
#  Testing:
#    needs: [Linter]
#    uses: github.com/iperon-org/app/.github/workflows/_testing.yaml@ci_cd
#    secrets:
#      gpg_password: ${{ secrets.GPG_PASSWORD }}
