name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  version:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
#          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build appbundle
      - run: flutter build ios --release --no-codesign

#  Linter:
#    uses: github.com/iperon-org/app/.github/workflows/_linter.yaml@ci_cd
#  Testing:
#    needs: [Linter]
#    uses: github.com/iperon-org/app/.github/workflows/_testing.yaml@ci_cd
#    secrets:
#      gpg_password: ${{ secrets.GPG_PASSWORD }}
