name: Release

#on:
#  release:
#    types:
#      - created

on:
  push:
    tags:
      - '*'

jobs:
  Release:
    name: "Build release"
    runs-on: macos-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Get Flutter Version
        id: flutter_version
        uses: bungabear/flutter_version_read@main
        with:
          file: ${{ github.workspace }}/pubspec.yaml

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: "Flutter config"
        run: flutter config --no-analytics

      - name: "Flutter pub get"
        run: flutter pub get

      - name: "Build apk"
        run: flutter build apk --release

      - name: "Build appbundle"
        run: flutter build appbundle --release

      - name: "Build ios"
        run: flutter build ios --release --no-codesign

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/ios/iphoneos/*.app,"

#          bodyFile: "body.md"

#      - name: "Upload artifact android application (apk)"
#        uses: actions/upload-artifact@v4
#        with:
#          name: iperon-android-${{ steps.flutter_version.outputs.version_number }}.apk
#          path: |
#            build/app/outputs/flutter-apk/app-release.apk
#          retention-days: 90
#
#      - name: "Upload artifact android application (abb)"
#        uses: actions/upload-artifact@v4
#        with:
#          name: iperon-android-${{ steps.flutter_version.outputs.version_number }}.abb
#          path: |
#            build/app/outputs/bundle/release/app-release.aab
#          retention-days: 90
#
#      - name: "Upload artifact ios application (app)"
#        uses: actions/upload-artifact@v4
#        with:
#          name: iperon-ios-${{ steps.flutter_version.outputs.version_number }}.app
#          path: |
#            build/ios/iphoneos/Runner.app
#          retention-days: 90
